### ISSUE TITLE
CodeSmith.Insight.Client Error

### ISSUE THREAD

**Issue by smithachalla** [codesmithtools/Templates#705]
Hello, 

I have been getting CodeSmith.Insight.ClientError whenever I right click and generate output.
It was working before but since the past couple of days, I have been having this problem. I am not sure what has changed in Visual studio except I have doing remote debugging. 

This is the error I get.I does not look like it is even trying to generate any files. Before the error occurs in less than 30 sec. We use codesmith 5.2. 
This is what the error xml says. Please suggest. Thank you
[codesmithError.txt](https://github.com/codesmithtools/Templates/files/114989/codesmithError.txt)
[LoadedModules.txt](https://github.com/codesmithtools/Templates/files/115047/LoadedModules.txt)

**Comment by niemyjski** [comment]
Hello,

I'm not able to read that error, but Generator 5.2 is no longer supported. I'd highly recommend upgrading to the latest version which is backwards compatible with 5.x and has many new features and fixes & been updated to support newer platforms
