### ISSUE TITLE
PLINQO

### ISSUE THREAD

**Issue by brufus** [codesmithtools/Templates#706]
Hello,
I'm evaluating codesmith with PLINQO for our department. I installed the trial version of codesmith and ran the PLINQO quick start to create a project connected to our sql database. If I set the web project as the startup I see all of the tables in the database on the left and as I click them the grid is populated accordingly so everything seems to work there.
We use primarily win-form applications in our department and now I'm trying to only access one table and populate a simple windows grid control with the table data but I don't see any examples of how to do that. Could you assist or point me in the right direction? We use VB.net but I cant even find a good example doing that in c#. 
[PLINQ.pdf](https://github.com/codesmithtools/Templates/files/350784/PLINQ.pdf)

**Comment by niemyjski** [comment]
Hello,

The created website is just ASP.NET Dynamic Data website, we don't generate any strongly typed controls or UI components for any of our templates. With this said you can easily data bind with the generated PLINQO templates. We just extend the linq-to-sql runtime. Here is a guide on databinding with win-forms:

* https://blogs.msdn.microsoft.com/wriju/2007/11/02/linq-to-sql-windows-form-binding-data-step-by-step/
* http://www.c-sharpcorner.com/article/data-binding-using-linq-to-sql-in-C-Sharp/
* http://www.codeproject.com/Articles/24656/A-Detailed-Data-Binding-Tutorial

Please let us know if you have any questions.
