### ISSUE TITLE
VS 2019 generate output for templates from Command line

### ISSUE THREAD

**Issue by schalla27** [codesmithtools/Templates#717]
We have contacted you in the past with this issue. 
https://github.com/codesmithtools/Templates/issues/712
Has this issue been resolved? Can I generate templates from a right menu with manage outputs in VS 2019? If integration with VS 2019 is blocked then what would be an alternative way to achieve the following. 

a) Currently in VS 2017, If we are generating a new output file from right click manage outputs, then this new file is automatically added to the project file and source control. 
b) If we are editing  existing files, then a check-out in source control is performed and then files are modified automatically. 
c) If right click integration is not available in VS 2019, can we achieve the same from the command line or any other way to achieve this? We could edit our existing template .csp files in order to add it to the project and source control? How do I do this. 
d) Keeping the codebase at VS 2017 is not an option just for codesmith tools integration with no eta. We will be behind in no time. 
e) How are other companies who use codesmith and VS 2019 get around this integration?

**Comment by niemyjski** [comment]
Until VS2019 is supported (we are currently blocked) you'll need to generate the templates outside of Visual Studio or inside Visual Studio using the vs terminal and then add all generated project files to the solution. Depending on your source control integration you may need to check out the files beforehand. This works like any other file created outside of Visual Studio that you wish to include in your VS Solution. I hope this helps.

Please contact support in the future for questions relating to generator. This is a template issue tracker.

**Comment by niemyjski** [comment]
Please see this for generating from the command line: https://codesmith.atlassian.net/wiki/spaces/Generator/pages/528893/Using+a+Generator+Project+from+Command-Line
