### ISSUE TITLE
Any plan to upgrade CSLA template to CSLA 5.4?

### ISSUE THREAD

**Issue by jlucv** [codesmithtools/Templates#719]
As I'm currently planning Blazor/CSLA development. with .NET 5, this would be wonderful.

Thanks.

**Comment by niemyjski** [comment]
We'd be open to accept any pr's that would add support for it. I'm not sure what exactly the changes would be to upgrade to CSLA 5.4? Do you have an idea of the scope of this work?

**Comment by jlucv** [comment]
Hello,

I really don’t know what is involve as efforts for template maintenance.
What I know is that there is a breaking change list for every CSLA major releases.

-JLuc

**Comment by niemyjski** [comment]
What I'd recommend doing is generate a small sample of one or two tables and then see what it takes to upgrade the nuget packages and get onto the latest version. It might not be very many changes to get on latest but I haven't tried it.

**Comment by jlucv** [comment]
I tried out an editable root class, did minor changes and compiled a .NET Standard library with CSLA 5.4.0  and SQLDataClient 4.8.2 for genrated DAL.I compiled and run a test console application in .NET 5.. I tested CRUD ok,

**Comment by niemyjski** [comment]
Awesome to hear it didn't take many changes!
